import { createFileRoute, Link } from "@tanstack/react-router";
import { breadcrumbSchema } from "../lib/seo";
import { ArrowUpRight, Compass, Map, Scissors, Users } from "lucide-react";
import { HubSpotBadge } from "../components/HubSpotBadge";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Revlyn | HubSpot and RevOps Partner" }, { name: "description", content: "Learn why Revlyn combines HubSpot expertise and revenue engineering for growing revenue teams." },
  { property: "og:url", content: "https://revlyn.io/about" }, { property: "og:title", content: "About Revlyn | HubSpot and RevOps Partner" }, { property: "og:description", content: "Our mission is to make CRM clear, connected, and useful for growing revenue teams." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:image", content: "https://revlyn.io/og-image.png" }, { name: "twitter:image", content: "https://revlyn.io/og-image.png" },
    { "script:ld+json": breadcrumbSchema([{ name: "About Revlyn", path: "/about" }]) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/about" }] }), component: AboutPage });

function AboutPage() { return <main id="top">
  <section className="reveal relative mx-auto grid min-h-[62vh] max-w-[92rem] content-center overflow-hidden rounded-b-[3.5rem] bg-brand/10 px-5 py-20 text-center lg:rounded-b-[6rem]"><div aria-hidden="true" className="absolute -left-28 top-8 size-80 rounded-full bg-sun/40 blur-3xl"/><div aria-hidden="true" className="absolute -right-20 bottom-0 size-96 rounded-full bg-mint/35 blur-3xl"/><div className="relative mx-auto max-w-5xl"><h1 className="font-display text-5xl font-bold leading-none sm:text-7xl lg:text-[6rem]">Built for growth.<br/><span className="text-brand">Grounded in</span> <span className="text-grape">real work.</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-ink/70 sm:text-xl">Revlyn has one focused mission: help growing companies turn CRM from software they own into a system their revenue teams use.</p><div className="mt-8"><Link to="/hubspot"><HubSpotBadge /></Link></div></div></section>
  <section className="reveal py-20 sm:py-28"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-6 lg:grid-cols-2"><div><h2 className="font-display text-4xl font-bold sm:text-6xl">Why Revlyn exists.</h2><p className="mt-6 text-lg leading-relaxed text-ink/65">Customer work often spreads across spreadsheets, inboxes, calls, chats, and individual memory. Buying a CRM does not connect that work by itself.</p><p className="mt-5 text-lg leading-relaxed text-ink/65">Revlyn brings the business process and the software together. We want teams to know what matters now, what happens next, and where to find the full customer story.</p></div><div className="rounded-[3rem] bg-ink p-8 text-cream sm:p-10"><Map className="text-mint" size={36}/><p className="mt-8 font-display text-3xl font-bold">How your team works is not a footnote.</p><p className="mt-5 leading-relaxed text-cream/65">Revenue teams can span offices, time zones, channels, and tools. We start with how your people actually sell, serve, and collaborate instead of forcing a borrowed playbook.</p></div></div></section>
  <section className="reveal border-y-2 border-ink/10 bg-background py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><h2 className="font-display text-4xl font-bold sm:text-6xl">What guides the work.</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{[[Compass,"bg-sun","Practical over complicated","The best system is not the one with the most features. It is the one the team can understand, trust, and maintain."],[Scissors,"bg-mint","Process before platform","We clarify how work should move before asking software to automate it."],[Users,"bg-grape text-cream","People shape the system","The people who use the CRM need a voice in its design and a clear role after launch."]].map(([Icon,tone,title,copy]) => { const I=Icon as typeof Compass; return <article key={title as string} className="rounded-[2.5rem] bg-cream p-8"><div className={`grid size-16 place-items-center rounded-2xl ${tone}`}><I size={27}/></div><h3 className="mt-6 text-2xl font-bold">{title as string}</h3><p className="mt-3 leading-relaxed text-ink/65">{copy as string}</p></article>})}</div></div></section>
  <section className="reveal py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[["01","Listen","Understand the daily work"],["02","Clarify","Make ownership visible"],["03","Connect","Bring context together"],["04","Improve","Keep learning after launch"]].map(([number,title,copy],i)=><article key={number} className={`rounded-[2rem] p-6 ${i===0?"bg-brand text-cream":i===1?"bg-sun":i===2?"bg-mint":"bg-grape text-cream"}`}><span className="text-sm font-bold opacity-60">{number}</span><h3 className="mt-8 text-2xl font-bold">{title}</h3><p className="mt-2 opacity-70">{copy}</p></article>)}</div></div></section>
  <section className="reveal mx-auto max-w-6xl px-5 pb-24 sm:px-6"><div className="rounded-[3rem] bg-ink p-10 text-center text-cream sm:p-16"><h2 className="font-display text-4xl font-bold sm:text-6xl">Let’s make CRM useful.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-cream/65">Tell us what is getting in the way of clear customer work.</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-sun px-8 py-4 font-bold text-ink">Start a conversation <ArrowUpRight size={19}/></Link></div></section>
</main> }