import { createFileRoute, Link } from "@tanstack/react-router";
import { breadcrumbSchema } from "../lib/seo";
import { ArrowUpRight, CalendarClock, Check, Mail, MessageSquare, RouteIcon } from "lucide-react";
import { MeetingsEmbed } from "@/components/MeetingsEmbed";

export const Route = createFileRoute("/book-a-call")({ head: () => ({ meta: [
  { title: "Book a Discovery Call | Revlyn" }, { name: "description", content: "Pick a time that suits you. A first conversation with Revlyn is for understanding your CRM situation, not pushing a package." },
  { property: "og:url", content: "https://revlyn.io/book-a-call" }, { property: "og:title", content: "Book a Discovery Call | Revlyn" }, { property: "og:description", content: "Choose a time on our calendar and talk through your CRM and revenue operations questions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:image", content: "https://revlyn.io/og-image.png" }, { name: "twitter:image", content: "https://revlyn.io/og-image.png" },
    { "script:ld+json": breadcrumbSchema([{ name: "Book a Discovery Call", path: "/book-a-call" }]) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/book-a-call" }] }), component: BookACallPage });

function BookACallPage() { return <main id="top">
  <section className="reveal relative mx-auto overflow-hidden rounded-b-[3.5rem] bg-mint/20 px-5 py-20 lg:rounded-b-[6rem]"><div aria-hidden="true" className="absolute -left-20 top-0 size-96 rounded-full bg-brand/15 blur-3xl"/><div aria-hidden="true" className="absolute right-0 top-20 size-96 rounded-full bg-sun/30 blur-3xl"/><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><h1 className="font-display text-5xl font-bold leading-none sm:text-7xl lg:text-[6rem]">Pick a time that <span className="text-brand">suits you.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-ink/70 sm:text-xl">A first conversation is for understanding your situation, not pushing a package. Choose any open slot on the calendar and we will call you.</p><p className="mt-5 text-ink/60">Prefer email? Write to <a href="mailto:info@revlyn.io?subject=CRM consultation" className="font-bold text-brand">info@revlyn.io</a>.</p></div><div className="rounded-[3rem] border border-background/70 bg-background/75 p-7 shadow-2xl backdrop-blur-xl sm:p-9"><CalendarClock className="text-brand" size={34}/><p className="mt-6 text-sm font-bold text-ink/50">Discovery call</p><p className="mt-2 font-display text-2xl font-bold text-grape sm:text-3xl">About 30 minutes</p><p className="mt-5 leading-relaxed text-ink/60">A focused conversation about where your CRM journey stands and what a better working day looks like for your team.</p></div></div></section>
  <section className="reveal py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><span className="grid size-16 place-items-center rounded-2xl bg-brand text-cream"><CalendarClock size={28} aria-hidden="true" /></span><h2 className="mt-6 font-display text-4xl font-bold sm:text-6xl">Book a discovery call.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-ink/70">The calendar shows our current availability across time zones. You will get a confirmation with a meeting link straight away.</p></div><div className="overflow-hidden rounded-[2.5rem] border-2 border-ink/5 bg-background p-4 shadow-2xl sm:p-6"><MeetingsEmbed /></div></div></div></section>
  <section className="reveal bg-sun/20 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><h2 className="font-display text-4xl font-bold sm:text-6xl">What helps us understand quickly.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[[RouteIcon,"bg-sun","Where you are","Choosing a first CRM, improving an existing one, or replacing a system that no longer fits."],[MessageSquare,"bg-mint","What feels difficult","The workflow, data, reporting, follow-up, handoff, or adoption issue creating the most friction."],[Check,"bg-grape text-cream","What better means","The outcome your team needs, such as clearer ownership, faster follow-up, or trusted reporting."]].map(([Icon,tone,title,copy])=>{const I=Icon as typeof RouteIcon;return <article key={title as string} className="rounded-[2.5rem] border-2 border-ink/5 bg-background p-8"><div className={`grid size-16 place-items-center rounded-2xl ${tone}`}><I size={26}/></div><h3 className="mt-6 text-2xl font-bold">{title as string}</h3><p className="mt-3 leading-relaxed text-ink/65">{copy as string}</p></article>})}</div></div></section>
  <section className="reveal py-20 text-center sm:py-28"><div className="mx-auto max-w-3xl px-5"><h2 className="font-display text-4xl font-bold sm:text-5xl">Want context before we talk?</h2><div className="mt-8 flex flex-wrap justify-center gap-4"><Link to="/services" className="rounded-2xl bg-brand px-7 py-4 font-bold text-cream">Explore services</Link><Link to="/how-we-work" className="rounded-2xl border-2 border-ink px-7 py-4 font-bold">How we work</Link></div></div></section>
</main> }
