import { createFileRoute, Link } from "@tanstack/react-router";
import { breadcrumbSchema } from "../lib/seo";
import { ArrowUpRight, CalendarClock, Check, Mail, MessageSquare, RouteIcon } from "lucide-react";
import { MeetingsEmbed } from "@/components/MeetingsEmbed";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact Revlyn | Discuss Your CRM" }, { name: "description", content: "Talk to Revlyn about CRM strategy, implementation, automation, data, integrations, reporting, or adoption." },
  { property: "og:url", content: "https://revlyn.io/contact" }, { property: "og:title", content: "Contact Revlyn | Discuss Your CRM" }, { property: "og:description", content: "Tell us what feels messy in your CRM today and start a practical conversation." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:image", content: "https://revlyn.io/og-image.png" }, { name: "twitter:image", content: "https://revlyn.io/og-image.png" },
    { "script:ld+json": breadcrumbSchema([{ name: "Contact Revlyn", path: "/contact" }]) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/contact" }] }), component: ContactPage });

function ContactPage() { return <main id="top">
  <section className="reveal relative mx-auto overflow-hidden rounded-b-[3.5rem] bg-sun/20 px-5 py-20 lg:rounded-b-[6rem]"><div aria-hidden="true" className="absolute -left-20 top-0 size-96 rounded-full bg-brand/15 blur-3xl"/><div aria-hidden="true" className="absolute right-0 top-20 size-96 rounded-full bg-mint/30 blur-3xl"/><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div><h1 className="font-display text-5xl font-bold leading-none sm:text-7xl lg:text-[6rem]">Tell us what feels <span className="text-brand">messy.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-ink/70 sm:text-xl">Share where your CRM journey stands, what your team is struggling with, and what a better working day should look like.</p><a href="mailto:info@revlyn.io?subject=CRM consultation" className="mt-9 inline-flex items-center gap-3 rounded-2xl bg-ink px-7 py-4 font-bold text-cream shadow-tactile-ink">Email Revlyn <ArrowUpRight size={19}/></a></div><div className="rounded-[3rem] border border-background/70 bg-background/75 p-7 shadow-2xl backdrop-blur-xl sm:p-9"><Mail className="text-brand" size={34}/><p className="mt-6 text-sm font-bold text-ink/50">Write to</p><a href="mailto:info@revlyn.io?subject=CRM consultation" className="mt-2 block break-all font-display text-2xl font-bold text-grape sm:text-3xl">info@revlyn.io</a><p className="mt-5 leading-relaxed text-ink/60">Use the subject “CRM consultation” so your message is easy to identify.</p></div></div></section>
  <section className="reveal py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><span className="grid size-16 place-items-center rounded-2xl bg-brand text-cream"><CalendarClock size={28} aria-hidden="true" /></span><h2 className="mt-6 font-display text-4xl font-bold sm:text-6xl">Book a discovery call.</h2><p className="mt-5 max-w-md text-lg leading-relaxed text-ink/70">Pick a time that suits you. A first conversation is for understanding your situation, not pushing a package.</p><p className="mt-5 text-ink/60">Prefer email? Write to <a href="mailto:info@revlyn.io?subject=CRM consultation" className="font-bold text-brand">info@revlyn.io</a>.</p></div><div className="overflow-hidden rounded-[2.5rem] border-2 border-ink/5 bg-background p-4 shadow-2xl sm:p-6"><MeetingsEmbed /></div></div></div></section>
  <section className="reveal bg-mint/15 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><h2 className="font-display text-4xl font-bold sm:text-6xl">What helps us understand quickly.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[[RouteIcon,"bg-sun","Where you are","Choosing a first CRM, improving an existing one, or replacing a system that no longer fits."],[MessageSquare,"bg-mint","What feels difficult","The workflow, data, reporting, follow-up, handoff, or adoption issue creating the most friction."],[Check,"bg-grape text-cream","What better means","The outcome your team needs, such as clearer ownership, faster follow-up, or trusted reporting."]].map(([Icon,tone,title,copy])=>{const I=Icon as typeof RouteIcon;return <article key={title as string} className="rounded-[2.5rem] border-2 border-ink/5 bg-background p-8"><div className={`grid size-16 place-items-center rounded-2xl ${tone}`}><I size={26}/></div><h3 className="mt-6 text-2xl font-bold">{title as string}</h3><p className="mt-3 leading-relaxed text-ink/65">{copy as string}</p></article>})}</div></div></section>
  <section className="reveal bg-ink py-20 text-cream sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-12 lg:grid-cols-2"><div><h2 className="font-display text-4xl font-bold sm:text-6xl">What happens next.</h2><p className="mt-5 max-w-lg text-lg text-cream/65">A first conversation is for understanding the problem, not forcing a solution.</p></div><div className="grid gap-4">{[["01","We read the context","We look for the business issue behind the CRM request."],["02","We ask focused questions","We clarify process, people, data, tools, and priorities."],["03","We suggest a sensible next step","That may be an audit, a focused improvement, or a broader implementation conversation."]].map(([n,t,c],i)=><div key={n} className="flex gap-5 rounded-[2rem] border border-cream/10 bg-cream/5 p-6"><span className={`grid size-10 shrink-0 place-items-center rounded-full font-bold text-ink ${i===0?"bg-sun":i===1?"bg-mint":"bg-brand text-cream"}`}>{n}</span><div><h3 className="text-xl font-bold">{t}</h3><p className="mt-2 text-cream/65">{c}</p></div></div>)}</div></div></div></section>
  <section className="reveal py-20 text-center sm:py-28"><div className="mx-auto max-w-3xl px-5"><h2 className="font-display text-4xl font-bold sm:text-5xl">Want context before you write?</h2><div className="mt-8 flex flex-wrap justify-center gap-4"><Link to="/services" className="rounded-2xl bg-brand px-7 py-4 font-bold text-cream">Explore services</Link><Link to="/crm-implementation" className="rounded-2xl border-2 border-ink px-7 py-4 font-bold">Read the CRM guide</Link></div></div></section>
</main> }