import { createFileRoute } from "@tanstack/react-router";
import { breadcrumbSchema } from "../lib/seo";

export const Route = createFileRoute("/privacy")({ head: () => ({ meta: [
  { title: "Privacy Policy | Revlyn" }, { name: "description", content: "How Revlyn handles information shared through this website and direct enquiries." }, { property: "og:url", content: "https://revlyn.io/privacy" }, { property: "og:title", content: "Privacy Policy | Revlyn" }, { property: "og:description", content: "How Revlyn handles information shared through this website and direct enquiries." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
    { "script:ld+json": breadcrumbSchema([{ name: "Privacy Policy", path: "/privacy" }]) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/privacy" }] }), component: PrivacyPage });

const sections = [
  ["Information you share", "When you contact Revlyn by email, you may share your name, work contact details, company information, and details about your CRM needs. Please avoid sending passwords, payment details, or sensitive personal data in an initial enquiry."],
  ["How information may be used", "Information you provide may be used to understand and respond to your enquiry, continue a business conversation, prepare a relevant proposal, and maintain appropriate business records."],
  ["Website information", "Basic technical information may be processed by the services that host and protect this website. If analytics or additional tracking tools are introduced, this notice should be updated to explain them."],
  ["Sharing and service providers", "Information may be handled by service providers needed to operate communication and website services. Revlyn does not sell personal information."],
  ["Retention and security", "Information is intended to be kept only as long as needed for the enquiry, an active business relationship, or applicable record-keeping obligations. Reasonable steps should be used to protect it."],
  ["Your choices", "You can ask what personal information is held about you, request a correction, or ask for deletion where appropriate by writing to the contact address below."],
];

function PrivacyPage(){return <main><section className="reveal bg-mint/20 px-5 py-20 sm:py-28"><div className="mx-auto max-w-4xl"><h1 className="font-display text-5xl font-bold sm:text-7xl">Privacy, in <span className="text-brand">plain words.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-ink/65">This page explains the basic way information shared through the Revlyn website and direct enquiries is intended to be handled.</p><p className="mt-5 text-sm font-bold text-ink/50">Last updated: 23 September 2026</p></div></section><section className="reveal py-20"><div className="mx-auto max-w-4xl space-y-5 px-5">{sections.map(([title,copy],i)=><article key={title} className="grid gap-5 rounded-[2rem] border-2 border-ink/5 bg-background p-7 sm:grid-cols-[auto_1fr]"><span className={`grid size-11 place-items-center rounded-xl font-bold ${i%3===0?"bg-sun":i%3===1?"bg-mint":"bg-brand text-cream"}`}>0{i+1}</span><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-3 leading-relaxed text-ink/65">{copy}</p></div></article>)}<div className="rounded-[2rem] bg-ink p-8 text-cream"><h2 className="text-2xl font-bold">Questions about your information</h2><p className="mt-3 text-cream/65">Write to <a className="font-bold text-sun" href="mailto:info@revlyn.io?subject=Privacy enquiry">info@revlyn.io</a> with the subject “Privacy enquiry”.</p><p className="mt-5 text-sm text-cream/45">This is a general website notice. It should be reviewed and updated as Revlyn adds forms, analytics, vendors, or formal service operations.</p></div></div></section></main>}