import { createFileRoute, Link } from "@tanstack/react-router";
import { breadcrumbSchema, serviceSchema } from "../lib/seo";
import { ArrowDown, ArrowRight, ArrowUpRight, Award, BarChart3, Check, Database, Link2, RouteIcon, Users, Workflow, Zap } from "lucide-react";

export const Route = createFileRoute("/services")({
  head: () => ({ meta: [
    { title: "HubSpot and RevOps Services for Growing Teams | Revlyn" },
    { name: "description", content: "HubSpot and RevOps services covering CRM strategy, implementation, data, automation, integrations, reporting, and adoption for growing teams." },
    { property: "og:url", content: "https://revlyn.io/services" }, { property: "og:title", content: "HubSpot and RevOps Services for Growing Teams | Revlyn" },
    { property: "og:description", content: "Practical CRM services designed around the way your sales team actually works." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:image", content: "https://revlyn.io/og-image.png" }, { name: "twitter:image", content: "https://revlyn.io/og-image.png" },
    { "script:ld+json": breadcrumbSchema([{ name: "HubSpot and RevOps Services for Growing Teams", path: "/services" }]) },
    { "script:ld+json": serviceSchema({ name: "HubSpot and RevOps Services for Growing Teams", description: "HubSpot and RevOps services covering CRM strategy, implementation, data, automation, integrations, reporting, and adoption for growing teams.", path: "/services" }) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/services" }] }),
  component: ServicesPage,
});

const services = [
  { id: "strategy", icon: RouteIcon, tone: "bg-sun", title: "CRM strategy and setup", question: "What should the system support?", copy: "We translate your sales process into clear stages, fields, roles, views, and rules. The result is a CRM structure that reflects how work should move, not a generic template.", includes: ["Current process and bottleneck review", "Pipeline, ownership, and field design", "Role, access, and governance decisions", "Configuration plan and priorities"] },
  { id: "data", icon: Database, tone: "bg-mint", title: "Customer data", question: "Can your team trust the record?", copy: "We help organise customer information so people can find the right context and reports can start from dependable data.", includes: ["Source and field mapping", "Duplicate and quality rules", "Migration planning and test imports", "Ongoing data ownership"] },
  { id: "automation", icon: Zap, tone: "bg-brand text-cream", title: "Sales automation", question: "What should happen without chasing?", copy: "We automate repeatable work while keeping judgement with people. Every workflow has a clear purpose, trigger, owner, and exception path.", includes: ["Lead routing and assignment", "Follow-up tasks and reminders", "Approvals and team handoffs", "Useful alerts and notifications"] },
  { id: "integrations", icon: Link2, tone: "bg-grape text-cream", title: "Tool integrations", question: "Where should information flow?", copy: "We connect the systems around your customer journey so teams spend less time moving information and more time acting on it.", includes: ["Website and lead-source capture", "Email and communication workflows", "Business system connections", "Integration testing and ownership"] },
  { id: "reporting", icon: BarChart3, tone: "bg-sun", title: "Reporting and insights", question: "Which decision should this answer?", copy: "We build practical views around pipeline health, team activity, data quality, and the questions leaders need to answer regularly.", includes: ["Pipeline and stage visibility", "Next-step and ageing views", "Data-quality monitoring", "Leadership review dashboards"] },
  { id: "adoption", icon: Users, tone: "bg-mint", title: "Team adoption", question: "Will the new way of working stick?", copy: "We support people through role-based guidance, launch routines, documentation, and feedback so the CRM becomes part of everyday work.", includes: ["Role-based walkthroughs", "Practical operating guides", "Usage and feedback reviews", "Post-launch improvements"] },
];

function ServicesPage() {
  return <main id="top">
    <section className="reveal relative isolate mx-auto grid min-h-[62vh] max-w-[92rem] content-center overflow-hidden rounded-b-[3.5rem] bg-mint/20 px-5 pb-20 pt-12 text-center sm:px-6 lg:min-h-[560px] lg:rounded-b-[6rem]">
      <div aria-hidden="true" className="absolute -left-20 top-8 size-80 rounded-full bg-brand/15 blur-3xl" /><div aria-hidden="true" className="absolute -right-16 top-0 size-80 rounded-full bg-grape/15 blur-3xl" /><div aria-hidden="true" className="absolute bottom-0 left-1/3 h-56 w-1/2 rounded-full bg-sun/25 blur-3xl" />
      <div className="relative mx-auto max-w-5xl"><h1 className="font-display text-5xl font-bold leading-[0.98] sm:text-7xl lg:text-[6rem]">The work behind a <span className="text-brand">CRM</span> that <span className="text-grape">works.</span></h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-ink/70 sm:text-xl">Bring us one difficult workflow or the whole customer journey. We connect process, data, tools, and people into one practical system.</p><a href="#service-list" className="mt-9 inline-flex items-center gap-2 font-bold text-ink/60 hover:text-brand">Explore the services <ArrowDown size={18} /></a></div>
    </section>
    <section id="service-list" className="reveal scroll-mt-8 py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="max-w-3xl"><h2 className="font-display text-4xl font-bold sm:text-6xl">Six connected capabilities.</h2><p className="mt-5 text-lg leading-relaxed text-ink/65">Each service can solve a focused problem. Together, they create a dependable operating system for customer relationships.</p></div><div className="mt-14 space-y-6">{services.map(({ id, icon: Icon, tone, title, question, copy, includes }, index) => <article id={id} key={title} className="scroll-mt-28 grid gap-7 rounded-[2.5rem] border-2 border-ink/5 bg-background p-7 shadow-sm sm:p-9 lg:grid-cols-[auto_0.9fr_1.1fr] lg:gap-10"><div className={`grid size-20 place-items-center rounded-[1.5rem] ${tone}`}><Icon size={30} /></div><div><p className="font-bold text-brand">{question}</p><h2 className="mt-2 font-display text-3xl font-bold">{title}</h2><p className="mt-4 leading-relaxed text-ink/65">{copy}</p></div><ul className="grid content-start gap-3 rounded-[1.75rem] bg-cream p-5">{includes.map((item) => <li key={item} className="flex gap-3 font-semibold"><span className={`mt-0.5 grid size-6 shrink-0 place-items-center rounded-full ${index % 2 ? "bg-sun" : "bg-mint"}`}><Check size={14} /></span>{item}</li>)}</ul></article>)}</div></div></section>
    <section className="reveal mx-auto max-w-6xl space-y-6 px-5 pb-4 sm:px-6"><Link to="/hubspot" className="group flex flex-col items-start gap-5 rounded-[3rem] border-2 border-sun/50 bg-sun/15 p-8 transition-transform duration-300 hover:-translate-y-1.5 sm:flex-row sm:items-center sm:justify-between sm:p-10"><div className="flex items-center gap-5"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-sun"><Award size={26} /></span><div><p className="font-display text-2xl font-bold sm:text-3xl">HubSpot Gold Partner</p><p className="mt-1 text-ink/60">Dedicated HubSpot onboarding, migration, automation, and adoption services.</p></div></div><span className="inline-flex items-center gap-2 font-bold text-brand">Explore HubSpot services <ArrowUpRight size={19} className="transition-transform group-hover:translate-x-1" /></span></Link><Link to="/revops" className="group flex flex-col items-start gap-5 rounded-[3rem] border-2 border-grape/40 bg-grape/10 p-8 transition-transform duration-300 hover:-translate-y-1.5 sm:flex-row sm:items-center sm:justify-between sm:p-10"><div className="flex items-center gap-5"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-grape text-cream"><Workflow size={26} /></span><div><p className="font-display text-2xl font-bold sm:text-3xl">Revenue operations</p><p className="mt-1 text-ink/60">One connected operation across marketing, sales, and service: process, data, and numbers your teams agree on.</p></div></div><span className="inline-flex items-center gap-2 font-bold text-grape">Explore RevOps <ArrowUpRight size={19} className="transition-transform group-hover:translate-x-1" /></span></Link></section>
    <section className="reveal bg-ink py-20 text-cream sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-6"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><h2 className="font-display text-4xl font-bold sm:text-6xl">Where should you start?</h2><div className="grid gap-4 sm:grid-cols-2">{[["Starting fresh","Define the process and requirements before choosing or configuring a CRM."],["CRM feels messy","Audit the current setup, data, usage, and bottlenecks before changing it."],["Manual work is growing","Map the repeatable steps and decide what should be automated."],["Reports are unreliable","Fix definitions, ownership, and data quality before adding dashboards."]].map(([title, copy], i) => <article key={title} className="rounded-[2rem] border border-cream/10 bg-cream/5 p-6"><span className={`grid size-9 place-items-center rounded-full font-bold text-ink ${i % 2 ? "bg-mint" : "bg-sun"}`}>{i+1}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-cream/65">{copy}</p></article>)}</div></div></div></section>
    <section className="reveal mx-auto max-w-6xl px-5 py-24 sm:px-6"><div className="rounded-[3rem] bg-mint p-8 sm:p-14"><h2 className="font-display text-4xl font-bold sm:text-6xl">Not sure which service fits?</h2><p className="mt-5 max-w-2xl text-lg text-ink/65">Start with the business problem. We can help separate the process, data, tool, and adoption issues before deciding what to change.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/contact" className="inline-flex items-center gap-2 rounded-2xl bg-ink px-7 py-4 font-bold text-cream">Talk to Revlyn <ArrowUpRight size={18} /></Link><Link to="/approach" className="inline-flex items-center gap-2 rounded-2xl border-2 border-ink px-7 py-4 font-bold">See our approach <ArrowRight size={18} /></Link></div></div></section>
  </main>;
}