import { createFileRoute } from "@tanstack/react-router";
import { breadcrumbSchema } from "../lib/seo";

export const Route = createFileRoute("/terms")({ head: () => ({ meta: [
  { title: "Website Terms | Revlyn" }, { name: "description", content: "Terms for using the Revlyn website and contacting the company about CRM services." }, { property: "og:url", content: "https://revlyn.io/terms" }, { property: "og:title", content: "Website Terms | Revlyn" }, { property: "og:description", content: "Terms for using the Revlyn website and contacting the company about CRM services." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
    { "script:ld+json": breadcrumbSchema([{ name: "Website Terms", path: "/terms" }]) },
  ], links: [{ rel: "canonical", href: "https://revlyn.io/terms" }] }), component: TermsPage });

const sections = [
  ["Using this website", "You may use this website to learn about Revlyn and make genuine business enquiries. Do not misuse the website, attempt to disrupt it, or use its content in a misleading or unlawful way."],
  ["Information is general", "Website content is provided for general information. CRM decisions depend on your process, data, tools, team, budget, and legal obligations. Content here is not a substitute for advice based on your specific situation."],
  ["Service enquiries", "Contacting Revlyn does not create a client relationship or commit either party to a project. Scope, responsibilities, fees, timing, confidentiality, and other commercial terms would need to be agreed separately in writing."],
  ["Intellectual property", "The Revlyn name, logo, website design, and original content belong to Revlyn unless stated otherwise. You may link to the website, but should not copy or present its materials as your own."],
  ["Third-party tools", "The website may refer to third-party products or services. Their availability, features, pricing, security, and terms are controlled by their providers. A reference does not imply a formal partnership or endorsement."],
  ["Availability and changes", "Revlyn may update, correct, move, or remove website content. Reasonable care is taken, but uninterrupted availability and complete accuracy cannot be guaranteed."],
];

function TermsPage(){return <main><section className="reveal bg-sun/25 px-5 py-20 sm:py-28"><div className="mx-auto max-w-4xl"><h1 className="font-display text-5xl font-bold sm:text-7xl">Clear terms for a <span className="text-grape">clear start.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-ink/65">These terms cover use of the Revlyn website and the first stage of a service enquiry.</p><p className="mt-5 text-sm font-bold text-ink/50">Last updated: 23 September 2026</p></div></section><section className="reveal py-20"><div className="mx-auto max-w-4xl space-y-5 px-5">{sections.map(([title,copy],i)=><article key={title} className="grid gap-5 rounded-[2rem] border-2 border-ink/5 bg-background p-7 sm:grid-cols-[auto_1fr]"><span className={`grid size-11 place-items-center rounded-xl font-bold ${i%3===0?"bg-brand text-cream":i%3===1?"bg-mint":"bg-grape text-cream"}`}>0{i+1}</span><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-3 leading-relaxed text-ink/65">{copy}</p></div></article>)}<div className="rounded-[2rem] bg-ink p-8 text-cream"><h2 className="text-2xl font-bold">Questions about these terms</h2><p className="mt-3 text-cream/65">Write to <a className="font-bold text-sun" href="mailto:info@revlyn.io?subject=Website terms enquiry">info@revlyn.io</a>.</p><p className="mt-5 text-sm text-cream/45">These are general website terms. Project-specific terms would be documented separately before work begins.</p></div></div></section></main>}