/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CompareRouteRouteImport } from './routes/compare/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmImplementationRouteImport } from './routes/crm-implementation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as HubspotRouteRouteImport } from './routes/hubspot/route'
import { Route as IndustriesRouteRouteImport } from './routes/industries/route'
import { Route as PartnershipsRouteRouteImport } from './routes/partnerships/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RevopsRouteRouteImport } from './routes/revops/route'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogHowToCleanCrmDataBeforeMigrationRouteImport } from './routes/blog/how-to-clean-crm-data-before-migration'
import { Route as BlogWhyCrmAdoptionFailsRouteImport } from './routes/blog/why-crm-adoption-fails'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareHubspotVsPipedriveRouteImport } from './routes/compare/hubspot-vs-pipedrive'
import { Route as CompareHubspotVsSalesforceRouteImport } from './routes/compare/hubspot-vs-salesforce'
import { Route as CompareHubspotVsZohoRouteImport } from './routes/compare/hubspot-vs-zoho'
import { Route as HubspotIndexRouteImport } from './routes/hubspot/index'
import { Route as HubspotAutomationRouteImport } from './routes/hubspot/automation'
import { Route as HubspotImplementationRouteImport } from './routes/hubspot/implementation'
import { Route as HubspotIntegrationsRouteImport } from './routes/hubspot/integrations'
import { Route as HubspotManagedRouteImport } from './routes/hubspot/managed'
import { Route as HubspotMigrationRouteImport } from './routes/hubspot/migration'
import { Route as HubspotOnboardingRouteImport } from './routes/hubspot/onboarding'
import { Route as HubspotReportingRouteImport } from './routes/hubspot/reporting'
import { Route as HubspotTrainingRouteImport } from './routes/hubspot/training'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesB2bSaasRouteImport } from './routes/industries/b2b-saas'
import { Route as IndustriesConsultingRouteImport } from './routes/industries/consulting'
import { Route as IndustriesD2cEcommerceRouteImport } from './routes/industries/d2c-ecommerce'
import { Route as IndustriesFieldServicesRouteImport } from './routes/industries/field-services'
import { Route as PartnershipsIndexRouteImport } from './routes/partnerships/index'
import { Route as PartnershipsBitscaleRouteImport } from './routes/partnerships/bitscale'
import { Route as PartnershipsHubspotRouteImport } from './routes/partnerships/hubspot'
import { Route as RevopsIndexRouteImport } from './routes/revops/index'
import { Route as RevopsAlignmentRouteImport } from './routes/revops/alignment'
import { Route as RevopsAuditRouteImport } from './routes/revops/audit'
import { Route as RevopsDataArchitectureRouteImport } from './routes/revops/data-architecture'
import { Route as RevopsHandoffRouteImport } from './routes/revops/handoff'
import { Route as RevopsPipelineRouteImport } from './routes/revops/pipeline'
import { Route as RevopsReportingRouteImport } from './routes/revops/reporting'
import { Route as RevopsRetainerRouteImport } from './routes/revops/retainer'
import { Route as RevopsStackRouteImport } from './routes/revops/stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRouteRoute = CompareRouteRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmImplementationRoute = CrmImplementationRouteImport.update({
  id: '/crm-implementation',
  path: '/crm-implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const HubspotRouteRoute = HubspotRouteRouteImport.update({
  id: '/hubspot',
  path: '/hubspot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRouteRoute = IndustriesRouteRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRouteRoute = PartnershipsRouteRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RevopsRouteRoute = RevopsRouteRouteImport.update({
  id: '/revops',
  path: '/revops',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogHowToCleanCrmDataBeforeMigrationRoute =
  BlogHowToCleanCrmDataBeforeMigrationRouteImport.update({
    id: '/how-to-clean-crm-data-before-migration',
    path: '/how-to-clean-crm-data-before-migration',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogWhyCrmAdoptionFailsRoute = BlogWhyCrmAdoptionFailsRouteImport.update({
  id: '/why-crm-adoption-fails',
  path: '/why-crm-adoption-fails',
  getParentRoute: () => BlogRouteRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRouteRoute,
} as any)
const CompareHubspotVsPipedriveRoute =
  CompareHubspotVsPipedriveRouteImport.update({
    id: '/hubspot-vs-pipedrive',
    path: '/hubspot-vs-pipedrive',
    getParentRoute: () => CompareRouteRoute,
  } as any)
const CompareHubspotVsSalesforceRoute =
  CompareHubspotVsSalesforceRouteImport.update({
    id: '/hubspot-vs-salesforce',
    path: '/hubspot-vs-salesforce',
    getParentRoute: () => CompareRouteRoute,
  } as any)
const CompareHubspotVsZohoRoute = CompareHubspotVsZohoRouteImport.update({
  id: '/hubspot-vs-zoho',
  path: '/hubspot-vs-zoho',
  getParentRoute: () => CompareRouteRoute,
} as any)
const HubspotIndexRoute = HubspotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotAutomationRoute = HubspotAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotImplementationRoute = HubspotImplementationRouteImport.update({
  id: '/implementation',
  path: '/implementation',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotIntegrationsRoute = HubspotIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotManagedRoute = HubspotManagedRouteImport.update({
  id: '/managed',
  path: '/managed',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotMigrationRoute = HubspotMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotOnboardingRoute = HubspotOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotReportingRoute = HubspotReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const HubspotTrainingRoute = HubspotTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => HubspotRouteRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRouteRoute,
} as any)
const IndustriesB2bSaasRoute = IndustriesB2bSaasRouteImport.update({
  id: '/b2b-saas',
  path: '/b2b-saas',
  getParentRoute: () => IndustriesRouteRoute,
} as any)
const IndustriesConsultingRoute = IndustriesConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => IndustriesRouteRoute,
} as any)
const IndustriesD2cEcommerceRoute = IndustriesD2cEcommerceRouteImport.update({
  id: '/d2c-ecommerce',
  path: '/d2c-ecommerce',
  getParentRoute: () => IndustriesRouteRoute,
} as any)
const IndustriesFieldServicesRoute = IndustriesFieldServicesRouteImport.update({
  id: '/field-services',
  path: '/field-services',
  getParentRoute: () => IndustriesRouteRoute,
} as any)
const PartnershipsIndexRoute = PartnershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnershipsRouteRoute,
} as any)
const PartnershipsBitscaleRoute = PartnershipsBitscaleRouteImport.update({
  id: '/bitscale',
  path: '/bitscale',
  getParentRoute: () => PartnershipsRouteRoute,
} as any)
const PartnershipsHubspotRoute = PartnershipsHubspotRouteImport.update({
  id: '/hubspot',
  path: '/hubspot',
  getParentRoute: () => PartnershipsRouteRoute,
} as any)
const RevopsIndexRoute = RevopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsAlignmentRoute = RevopsAlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsAuditRoute = RevopsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsDataArchitectureRoute = RevopsDataArchitectureRouteImport.update({
  id: '/data-architecture',
  path: '/data-architecture',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsHandoffRoute = RevopsHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsPipelineRoute = RevopsPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsReportingRoute = RevopsReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsRetainerRoute = RevopsRetainerRouteImport.update({
  id: '/retainer',
  path: '/retainer',
  getParentRoute: () => RevopsRouteRoute,
} as any)
const RevopsStackRoute = RevopsStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => RevopsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/compare': typeof CompareRouteRouteWithChildren
  '/hubspot': typeof HubspotRouteRouteWithChildren
  '/industries': typeof IndustriesRouteRouteWithChildren
  '/partnerships': typeof PartnershipsRouteRouteWithChildren
  '/revops': typeof RevopsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/crm-implementation': typeof CrmImplementationRoute
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-clean-crm-data-before-migration': typeof BlogHowToCleanCrmDataBeforeMigrationRoute
  '/blog/why-crm-adoption-fails': typeof BlogWhyCrmAdoptionFailsRoute
  '/compare/hubspot-vs-pipedrive': typeof CompareHubspotVsPipedriveRoute
  '/compare/hubspot-vs-salesforce': typeof CompareHubspotVsSalesforceRoute
  '/compare/hubspot-vs-zoho': typeof CompareHubspotVsZohoRoute
  '/hubspot/automation': typeof HubspotAutomationRoute
  '/hubspot/implementation': typeof HubspotImplementationRoute
  '/hubspot/integrations': typeof HubspotIntegrationsRoute
  '/hubspot/managed': typeof HubspotManagedRoute
  '/hubspot/migration': typeof HubspotMigrationRoute
  '/hubspot/onboarding': typeof HubspotOnboardingRoute
  '/hubspot/reporting': typeof HubspotReportingRoute
  '/hubspot/training': typeof HubspotTrainingRoute
  '/industries/b2b-saas': typeof IndustriesB2bSaasRoute
  '/industries/consulting': typeof IndustriesConsultingRoute
  '/industries/d2c-ecommerce': typeof IndustriesD2cEcommerceRoute
  '/industries/field-services': typeof IndustriesFieldServicesRoute
  '/partnerships/bitscale': typeof PartnershipsBitscaleRoute
  '/partnerships/hubspot': typeof PartnershipsHubspotRoute
  '/revops/alignment': typeof RevopsAlignmentRoute
  '/revops/audit': typeof RevopsAuditRoute
  '/revops/data-architecture': typeof RevopsDataArchitectureRoute
  '/revops/handoff': typeof RevopsHandoffRoute
  '/revops/pipeline': typeof RevopsPipelineRoute
  '/revops/reporting': typeof RevopsReportingRoute
  '/revops/retainer': typeof RevopsRetainerRoute
  '/revops/stack': typeof RevopsStackRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/hubspot/': typeof HubspotIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/revops/': typeof RevopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/crm-implementation': typeof CrmImplementationRoute
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-clean-crm-data-before-migration': typeof BlogHowToCleanCrmDataBeforeMigrationRoute
  '/blog/why-crm-adoption-fails': typeof BlogWhyCrmAdoptionFailsRoute
  '/compare/hubspot-vs-pipedrive': typeof CompareHubspotVsPipedriveRoute
  '/compare/hubspot-vs-salesforce': typeof CompareHubspotVsSalesforceRoute
  '/compare/hubspot-vs-zoho': typeof CompareHubspotVsZohoRoute
  '/hubspot/automation': typeof HubspotAutomationRoute
  '/hubspot/implementation': typeof HubspotImplementationRoute
  '/hubspot/integrations': typeof HubspotIntegrationsRoute
  '/hubspot/managed': typeof HubspotManagedRoute
  '/hubspot/migration': typeof HubspotMigrationRoute
  '/hubspot/onboarding': typeof HubspotOnboardingRoute
  '/hubspot/reporting': typeof HubspotReportingRoute
  '/hubspot/training': typeof HubspotTrainingRoute
  '/industries/b2b-saas': typeof IndustriesB2bSaasRoute
  '/industries/consulting': typeof IndustriesConsultingRoute
  '/industries/d2c-ecommerce': typeof IndustriesD2cEcommerceRoute
  '/industries/field-services': typeof IndustriesFieldServicesRoute
  '/partnerships/bitscale': typeof PartnershipsBitscaleRoute
  '/partnerships/hubspot': typeof PartnershipsHubspotRoute
  '/revops/alignment': typeof RevopsAlignmentRoute
  '/revops/audit': typeof RevopsAuditRoute
  '/revops/data-architecture': typeof RevopsDataArchitectureRoute
  '/revops/handoff': typeof RevopsHandoffRoute
  '/revops/pipeline': typeof RevopsPipelineRoute
  '/revops/reporting': typeof RevopsReportingRoute
  '/revops/retainer': typeof RevopsRetainerRoute
  '/revops/stack': typeof RevopsStackRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/hubspot': typeof HubspotIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/partnerships': typeof PartnershipsIndexRoute
  '/revops': typeof RevopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/compare': typeof CompareRouteRouteWithChildren
  '/hubspot': typeof HubspotRouteRouteWithChildren
  '/industries': typeof IndustriesRouteRouteWithChildren
  '/partnerships': typeof PartnershipsRouteRouteWithChildren
  '/revops': typeof RevopsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/book-a-call': typeof BookACallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/crm-implementation': typeof CrmImplementationRoute
  '/faq': typeof FaqRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-clean-crm-data-before-migration': typeof BlogHowToCleanCrmDataBeforeMigrationRoute
  '/blog/why-crm-adoption-fails': typeof BlogWhyCrmAdoptionFailsRoute
  '/compare/hubspot-vs-pipedrive': typeof CompareHubspotVsPipedriveRoute
  '/compare/hubspot-vs-salesforce': typeof CompareHubspotVsSalesforceRoute
  '/compare/hubspot-vs-zoho': typeof CompareHubspotVsZohoRoute
  '/hubspot/automation': typeof HubspotAutomationRoute
  '/hubspot/implementation': typeof HubspotImplementationRoute
  '/hubspot/integrations': typeof HubspotIntegrationsRoute
  '/hubspot/managed': typeof HubspotManagedRoute
  '/hubspot/migration': typeof HubspotMigrationRoute
  '/hubspot/onboarding': typeof HubspotOnboardingRoute
  '/hubspot/reporting': typeof HubspotReportingRoute
  '/hubspot/training': typeof HubspotTrainingRoute
  '/industries/b2b-saas': typeof IndustriesB2bSaasRoute
  '/industries/consulting': typeof IndustriesConsultingRoute
  '/industries/d2c-ecommerce': typeof IndustriesD2cEcommerceRoute
  '/industries/field-services': typeof IndustriesFieldServicesRoute
  '/partnerships/bitscale': typeof PartnershipsBitscaleRoute
  '/partnerships/hubspot': typeof PartnershipsHubspotRoute
  '/revops/alignment': typeof RevopsAlignmentRoute
  '/revops/audit': typeof RevopsAuditRoute
  '/revops/data-architecture': typeof RevopsDataArchitectureRoute
  '/revops/handoff': typeof RevopsHandoffRoute
  '/revops/pipeline': typeof RevopsPipelineRoute
  '/revops/reporting': typeof RevopsReportingRoute
  '/revops/retainer': typeof RevopsRetainerRoute
  '/revops/stack': typeof RevopsStackRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/hubspot/': typeof HubspotIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/revops/': typeof RevopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/compare'
    | '/hubspot'
    | '/industries'
    | '/partnerships'
    | '/revops'
    | '/about'
    | '/approach'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/crm-implementation'
    | '/faq'
    | '/how-we-work'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/how-to-clean-crm-data-before-migration'
    | '/blog/why-crm-adoption-fails'
    | '/compare/hubspot-vs-pipedrive'
    | '/compare/hubspot-vs-salesforce'
    | '/compare/hubspot-vs-zoho'
    | '/hubspot/automation'
    | '/hubspot/implementation'
    | '/hubspot/integrations'
    | '/hubspot/managed'
    | '/hubspot/migration'
    | '/hubspot/onboarding'
    | '/hubspot/reporting'
    | '/hubspot/training'
    | '/industries/b2b-saas'
    | '/industries/consulting'
    | '/industries/d2c-ecommerce'
    | '/industries/field-services'
    | '/partnerships/bitscale'
    | '/partnerships/hubspot'
    | '/revops/alignment'
    | '/revops/audit'
    | '/revops/data-architecture'
    | '/revops/handoff'
    | '/revops/pipeline'
    | '/revops/reporting'
    | '/revops/retainer'
    | '/revops/stack'
    | '/blog/'
    | '/compare/'
    | '/hubspot/'
    | '/industries/'
    | '/partnerships/'
    | '/revops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/crm-implementation'
    | '/faq'
    | '/how-we-work'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/how-to-clean-crm-data-before-migration'
    | '/blog/why-crm-adoption-fails'
    | '/compare/hubspot-vs-pipedrive'
    | '/compare/hubspot-vs-salesforce'
    | '/compare/hubspot-vs-zoho'
    | '/hubspot/automation'
    | '/hubspot/implementation'
    | '/hubspot/integrations'
    | '/hubspot/managed'
    | '/hubspot/migration'
    | '/hubspot/onboarding'
    | '/hubspot/reporting'
    | '/hubspot/training'
    | '/industries/b2b-saas'
    | '/industries/consulting'
    | '/industries/d2c-ecommerce'
    | '/industries/field-services'
    | '/partnerships/bitscale'
    | '/partnerships/hubspot'
    | '/revops/alignment'
    | '/revops/audit'
    | '/revops/data-architecture'
    | '/revops/handoff'
    | '/revops/pipeline'
    | '/revops/reporting'
    | '/revops/retainer'
    | '/revops/stack'
    | '/blog'
    | '/compare'
    | '/hubspot'
    | '/industries'
    | '/partnerships'
    | '/revops'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/compare'
    | '/hubspot'
    | '/industries'
    | '/partnerships'
    | '/revops'
    | '/about'
    | '/approach'
    | '/book-a-call'
    | '/case-studies'
    | '/contact'
    | '/crm-implementation'
    | '/faq'
    | '/how-we-work'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/blog/how-to-clean-crm-data-before-migration'
    | '/blog/why-crm-adoption-fails'
    | '/compare/hubspot-vs-pipedrive'
    | '/compare/hubspot-vs-salesforce'
    | '/compare/hubspot-vs-zoho'
    | '/hubspot/automation'
    | '/hubspot/implementation'
    | '/hubspot/integrations'
    | '/hubspot/managed'
    | '/hubspot/migration'
    | '/hubspot/onboarding'
    | '/hubspot/reporting'
    | '/hubspot/training'
    | '/industries/b2b-saas'
    | '/industries/consulting'
    | '/industries/d2c-ecommerce'
    | '/industries/field-services'
    | '/partnerships/bitscale'
    | '/partnerships/hubspot'
    | '/revops/alignment'
    | '/revops/audit'
    | '/revops/data-architecture'
    | '/revops/handoff'
    | '/revops/pipeline'
    | '/revops/reporting'
    | '/revops/retainer'
    | '/revops/stack'
    | '/blog/'
    | '/compare/'
    | '/hubspot/'
    | '/industries/'
    | '/partnerships/'
    | '/revops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  CompareRouteRoute: typeof CompareRouteRouteWithChildren
  HubspotRouteRoute: typeof HubspotRouteRouteWithChildren
  IndustriesRouteRoute: typeof IndustriesRouteRouteWithChildren
  PartnershipsRouteRoute: typeof PartnershipsRouteRouteWithChildren
  RevopsRouteRoute: typeof RevopsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  BookACallRoute: typeof BookACallRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CrmImplementationRoute: typeof CrmImplementationRoute
  FaqRoute: typeof FaqRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-implementation': {
      id: '/crm-implementation'
      path: '/crm-implementation'
      fullPath: '/crm-implementation'
      preLoaderRoute: typeof CrmImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubspot': {
      id: '/hubspot'
      path: '/hubspot'
      fullPath: '/hubspot'
      preLoaderRoute: typeof HubspotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revops': {
      id: '/revops'
      path: '/revops'
      fullPath: '/revops'
      preLoaderRoute: typeof RevopsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/how-to-clean-crm-data-before-migration': {
      id: '/blog/how-to-clean-crm-data-before-migration'
      path: '/how-to-clean-crm-data-before-migration'
      fullPath: '/blog/how-to-clean-crm-data-before-migration'
      preLoaderRoute: typeof BlogHowToCleanCrmDataBeforeMigrationRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/why-crm-adoption-fails': {
      id: '/blog/why-crm-adoption-fails'
      path: '/why-crm-adoption-fails'
      fullPath: '/blog/why-crm-adoption-fails'
      preLoaderRoute: typeof BlogWhyCrmAdoptionFailsRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/compare/hubspot-vs-pipedrive': {
      id: '/compare/hubspot-vs-pipedrive'
      path: '/hubspot-vs-pipedrive'
      fullPath: '/compare/hubspot-vs-pipedrive'
      preLoaderRoute: typeof CompareHubspotVsPipedriveRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/compare/hubspot-vs-salesforce': {
      id: '/compare/hubspot-vs-salesforce'
      path: '/hubspot-vs-salesforce'
      fullPath: '/compare/hubspot-vs-salesforce'
      preLoaderRoute: typeof CompareHubspotVsSalesforceRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/compare/hubspot-vs-zoho': {
      id: '/compare/hubspot-vs-zoho'
      path: '/hubspot-vs-zoho'
      fullPath: '/compare/hubspot-vs-zoho'
      preLoaderRoute: typeof CompareHubspotVsZohoRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/hubspot/': {
      id: '/hubspot/'
      path: '/'
      fullPath: '/hubspot/'
      preLoaderRoute: typeof HubspotIndexRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/automation': {
      id: '/hubspot/automation'
      path: '/automation'
      fullPath: '/hubspot/automation'
      preLoaderRoute: typeof HubspotAutomationRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/implementation': {
      id: '/hubspot/implementation'
      path: '/implementation'
      fullPath: '/hubspot/implementation'
      preLoaderRoute: typeof HubspotImplementationRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/integrations': {
      id: '/hubspot/integrations'
      path: '/integrations'
      fullPath: '/hubspot/integrations'
      preLoaderRoute: typeof HubspotIntegrationsRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/managed': {
      id: '/hubspot/managed'
      path: '/managed'
      fullPath: '/hubspot/managed'
      preLoaderRoute: typeof HubspotManagedRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/migration': {
      id: '/hubspot/migration'
      path: '/migration'
      fullPath: '/hubspot/migration'
      preLoaderRoute: typeof HubspotMigrationRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/onboarding': {
      id: '/hubspot/onboarding'
      path: '/onboarding'
      fullPath: '/hubspot/onboarding'
      preLoaderRoute: typeof HubspotOnboardingRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/reporting': {
      id: '/hubspot/reporting'
      path: '/reporting'
      fullPath: '/hubspot/reporting'
      preLoaderRoute: typeof HubspotReportingRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/hubspot/training': {
      id: '/hubspot/training'
      path: '/training'
      fullPath: '/hubspot/training'
      preLoaderRoute: typeof HubspotTrainingRouteImport
      parentRoute: typeof HubspotRouteRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRouteRoute
    }
    '/industries/b2b-saas': {
      id: '/industries/b2b-saas'
      path: '/b2b-saas'
      fullPath: '/industries/b2b-saas'
      preLoaderRoute: typeof IndustriesB2bSaasRouteImport
      parentRoute: typeof IndustriesRouteRoute
    }
    '/industries/consulting': {
      id: '/industries/consulting'
      path: '/consulting'
      fullPath: '/industries/consulting'
      preLoaderRoute: typeof IndustriesConsultingRouteImport
      parentRoute: typeof IndustriesRouteRoute
    }
    '/industries/d2c-ecommerce': {
      id: '/industries/d2c-ecommerce'
      path: '/d2c-ecommerce'
      fullPath: '/industries/d2c-ecommerce'
      preLoaderRoute: typeof IndustriesD2cEcommerceRouteImport
      parentRoute: typeof IndustriesRouteRoute
    }
    '/industries/field-services': {
      id: '/industries/field-services'
      path: '/field-services'
      fullPath: '/industries/field-services'
      preLoaderRoute: typeof IndustriesFieldServicesRouteImport
      parentRoute: typeof IndustriesRouteRoute
    }
    '/partnerships/': {
      id: '/partnerships/'
      path: '/'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsIndexRouteImport
      parentRoute: typeof PartnershipsRouteRoute
    }
    '/partnerships/bitscale': {
      id: '/partnerships/bitscale'
      path: '/bitscale'
      fullPath: '/partnerships/bitscale'
      preLoaderRoute: typeof PartnershipsBitscaleRouteImport
      parentRoute: typeof PartnershipsRouteRoute
    }
    '/partnerships/hubspot': {
      id: '/partnerships/hubspot'
      path: '/hubspot'
      fullPath: '/partnerships/hubspot'
      preLoaderRoute: typeof PartnershipsHubspotRouteImport
      parentRoute: typeof PartnershipsRouteRoute
    }
    '/revops/': {
      id: '/revops/'
      path: '/'
      fullPath: '/revops/'
      preLoaderRoute: typeof RevopsIndexRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/alignment': {
      id: '/revops/alignment'
      path: '/alignment'
      fullPath: '/revops/alignment'
      preLoaderRoute: typeof RevopsAlignmentRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/audit': {
      id: '/revops/audit'
      path: '/audit'
      fullPath: '/revops/audit'
      preLoaderRoute: typeof RevopsAuditRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/data-architecture': {
      id: '/revops/data-architecture'
      path: '/data-architecture'
      fullPath: '/revops/data-architecture'
      preLoaderRoute: typeof RevopsDataArchitectureRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/handoff': {
      id: '/revops/handoff'
      path: '/handoff'
      fullPath: '/revops/handoff'
      preLoaderRoute: typeof RevopsHandoffRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/pipeline': {
      id: '/revops/pipeline'
      path: '/pipeline'
      fullPath: '/revops/pipeline'
      preLoaderRoute: typeof RevopsPipelineRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/reporting': {
      id: '/revops/reporting'
      path: '/reporting'
      fullPath: '/revops/reporting'
      preLoaderRoute: typeof RevopsReportingRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/retainer': {
      id: '/revops/retainer'
      path: '/retainer'
      fullPath: '/revops/retainer'
      preLoaderRoute: typeof RevopsRetainerRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
    '/revops/stack': {
      id: '/revops/stack'
      path: '/stack'
      fullPath: '/revops/stack'
      preLoaderRoute: typeof RevopsStackRouteImport
      parentRoute: typeof RevopsRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogHowToCleanCrmDataBeforeMigrationRoute: typeof BlogHowToCleanCrmDataBeforeMigrationRoute
  BlogWhyCrmAdoptionFailsRoute: typeof BlogWhyCrmAdoptionFailsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogHowToCleanCrmDataBeforeMigrationRoute:
    BlogHowToCleanCrmDataBeforeMigrationRoute,
  BlogWhyCrmAdoptionFailsRoute: BlogWhyCrmAdoptionFailsRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface CompareRouteRouteChildren {
  CompareHubspotVsPipedriveRoute: typeof CompareHubspotVsPipedriveRoute
  CompareHubspotVsSalesforceRoute: typeof CompareHubspotVsSalesforceRoute
  CompareHubspotVsZohoRoute: typeof CompareHubspotVsZohoRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteRouteChildren: CompareRouteRouteChildren = {
  CompareHubspotVsPipedriveRoute: CompareHubspotVsPipedriveRoute,
  CompareHubspotVsSalesforceRoute: CompareHubspotVsSalesforceRoute,
  CompareHubspotVsZohoRoute: CompareHubspotVsZohoRoute,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteRouteWithChildren = CompareRouteRoute._addFileChildren(
  CompareRouteRouteChildren,
)

interface HubspotRouteRouteChildren {
  HubspotAutomationRoute: typeof HubspotAutomationRoute
  HubspotImplementationRoute: typeof HubspotImplementationRoute
  HubspotIntegrationsRoute: typeof HubspotIntegrationsRoute
  HubspotManagedRoute: typeof HubspotManagedRoute
  HubspotMigrationRoute: typeof HubspotMigrationRoute
  HubspotOnboardingRoute: typeof HubspotOnboardingRoute
  HubspotReportingRoute: typeof HubspotReportingRoute
  HubspotTrainingRoute: typeof HubspotTrainingRoute
  HubspotIndexRoute: typeof HubspotIndexRoute
}

const HubspotRouteRouteChildren: HubspotRouteRouteChildren = {
  HubspotAutomationRoute: HubspotAutomationRoute,
  HubspotImplementationRoute: HubspotImplementationRoute,
  HubspotIntegrationsRoute: HubspotIntegrationsRoute,
  HubspotManagedRoute: HubspotManagedRoute,
  HubspotMigrationRoute: HubspotMigrationRoute,
  HubspotOnboardingRoute: HubspotOnboardingRoute,
  HubspotReportingRoute: HubspotReportingRoute,
  HubspotTrainingRoute: HubspotTrainingRoute,
  HubspotIndexRoute: HubspotIndexRoute,
}

const HubspotRouteRouteWithChildren = HubspotRouteRoute._addFileChildren(
  HubspotRouteRouteChildren,
)

interface IndustriesRouteRouteChildren {
  IndustriesB2bSaasRoute: typeof IndustriesB2bSaasRoute
  IndustriesConsultingRoute: typeof IndustriesConsultingRoute
  IndustriesD2cEcommerceRoute: typeof IndustriesD2cEcommerceRoute
  IndustriesFieldServicesRoute: typeof IndustriesFieldServicesRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteRouteChildren: IndustriesRouteRouteChildren = {
  IndustriesB2bSaasRoute: IndustriesB2bSaasRoute,
  IndustriesConsultingRoute: IndustriesConsultingRoute,
  IndustriesD2cEcommerceRoute: IndustriesD2cEcommerceRoute,
  IndustriesFieldServicesRoute: IndustriesFieldServicesRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteRouteWithChildren = IndustriesRouteRoute._addFileChildren(
  IndustriesRouteRouteChildren,
)

interface PartnershipsRouteRouteChildren {
  PartnershipsBitscaleRoute: typeof PartnershipsBitscaleRoute
  PartnershipsHubspotRoute: typeof PartnershipsHubspotRoute
  PartnershipsIndexRoute: typeof PartnershipsIndexRoute
}

const PartnershipsRouteRouteChildren: PartnershipsRouteRouteChildren = {
  PartnershipsBitscaleRoute: PartnershipsBitscaleRoute,
  PartnershipsHubspotRoute: PartnershipsHubspotRoute,
  PartnershipsIndexRoute: PartnershipsIndexRoute,
}

const PartnershipsRouteRouteWithChildren =
  PartnershipsRouteRoute._addFileChildren(PartnershipsRouteRouteChildren)

interface RevopsRouteRouteChildren {
  RevopsAlignmentRoute: typeof RevopsAlignmentRoute
  RevopsAuditRoute: typeof RevopsAuditRoute
  RevopsDataArchitectureRoute: typeof RevopsDataArchitectureRoute
  RevopsHandoffRoute: typeof RevopsHandoffRoute
  RevopsPipelineRoute: typeof RevopsPipelineRoute
  RevopsReportingRoute: typeof RevopsReportingRoute
  RevopsRetainerRoute: typeof RevopsRetainerRoute
  RevopsStackRoute: typeof RevopsStackRoute
  RevopsIndexRoute: typeof RevopsIndexRoute
}

const RevopsRouteRouteChildren: RevopsRouteRouteChildren = {
  RevopsAlignmentRoute: RevopsAlignmentRoute,
  RevopsAuditRoute: RevopsAuditRoute,
  RevopsDataArchitectureRoute: RevopsDataArchitectureRoute,
  RevopsHandoffRoute: RevopsHandoffRoute,
  RevopsPipelineRoute: RevopsPipelineRoute,
  RevopsReportingRoute: RevopsReportingRoute,
  RevopsRetainerRoute: RevopsRetainerRoute,
  RevopsStackRoute: RevopsStackRoute,
  RevopsIndexRoute: RevopsIndexRoute,
}

const RevopsRouteRouteWithChildren = RevopsRouteRoute._addFileChildren(
  RevopsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  CompareRouteRoute: CompareRouteRouteWithChildren,
  HubspotRouteRoute: HubspotRouteRouteWithChildren,
  IndustriesRouteRoute: IndustriesRouteRouteWithChildren,
  PartnershipsRouteRoute: PartnershipsRouteRouteWithChildren,
  RevopsRouteRoute: RevopsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  BookACallRoute: BookACallRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CrmImplementationRoute: CrmImplementationRoute,
  FaqRoute: FaqRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
